[tool.black]
line-length = 100
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.githooks
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | yoyo
  )/
  | setup.py
)
'''

[tool.isort]
skip = "setup.py"
line_length = 100
balanced_wrapping = true
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[tool.coverage.run]
omit = ["setup.py", "tests/*"]
[tool.coverage.report]
omit = ["setup.py", "tests/*"]
